### ISSUE TITLE
Make next and prev arrows the same in home and post page layout

### ISSUE THREAD

**Issue by HazemSamir** [chesterhow/tale#13]
I think it'd be nice to have the next and previous arrows to be the same in both home and post layout:

Currently:
**In post:** left arrow links to the next page and right arrow links to the prev page.
**In home:** left arrow links to the prev page and right arrow links to the next page.

I suggest changing the post layout to align with the home page.

**Comment by chesterhow** [comment]
Hi thanks for the feedback. Ahh, that’s an interesting observation! I see it in a different way though. Here’s my thought process when I coded it as such:

The posts are sorted by newest first in the home page. So pressing the right arrow on the home page would be to show older posts. Similarly, in a post, pressing the right arrow would be to show an older post. And that was how I decided on the directions. 

What do you think? :)

**Comment by HazemSamir** [comment]
Your choice seems logical to me :smiley: but I'm used to having the next (new) post to the right not the left, that's why it got my attention. It seems like a personal preference.

I'd suggest adding text like "old posts" and "new post" next to the arrows to make them clearer (at least to me :smiley:)

**Comment by chesterhow** [comment]
Mhmm that sounds like quite a useful idea! I’ll try to see how to best implement this :)
