### ISSUE TITLE
Copyright holder

### ISSUE THREAD

**Issue by plutago** [chesterhow/tale#2]
Am I allowed to change the copyright holder?

Original:
```
<footer>
      <span>
        &copy; <time datetime="{{ site.time }}">{{ site.time | date: '%Y' }}</time> Chester How. All rights reserved.
      </span>
    </footer>
```

Original:
```
<footer>
      <span>
        &copy; <time datetime="{{ site.time }}">{{ site.time | date: '%Y' }}</time> {{ site.author.name }}. All rights reserved.
      </span>
    </footer>
```

**Comment by chesterhow** [comment]
Ah yes sure sure. Actually, could you make a PR for this too? :)

**Comment by plutago** [comment]
No need, you already did. 😉

**Comment by samuelgoto** [comment]
Would it be possible to make this configurable? E.g. if I wanted to use my own footer, would I be able to using _includes/footer.html?

Seems like right now the footer is hard coded:
https://github.com/chesterhow/tale/blob/master/_layouts/default.html#L25

**Comment by chesterhow** [comment]
@samuelgoto I hard coded it because it's meant to give credit to the blog's author and the theme itself. So I don't think this is something I want to change, at least not for now. If you really require a custom footer, feel free to fork the repo and customize it from there 😊

**Comment by samuelgoto** [comment]
Sounds good to me, will do. Thanks.

(apologies for the brevity, sent from phone)
