### ISSUE TITLE
Emoji is always displayed in a new line

### ISSUE THREAD

**Issue by abdalimran** [chesterhow/tale#24]
Emoji is always getting displayed in a new line and center aligned. I'm using gemoji.

**Comment by abdalimran** [comment]
Solved this issue by adding the following line-

```
img.emoji {
    display: inline-block;
    left: 0;
    transform: none;
    width: 20px;
    height: 20px;
    vertical-align: text-top;
    padding: 0;
    margin: 0;
}
```

**Comment by chesterhow** [comment]
Ah, this looks good. Would you like to make a pull request? Also, it would be better to change the height and the width to `1rem` instead since the font size changes with the screen size.
