### ISSUE TITLE
Post title with background image

### ISSUE THREAD

**Issue by GammaGames** [chesterhow/tale#27]
Overall this is my favorite theme so far, but I'm curious how difficult it would be to modify a post to use an image in the background of a post title, similar to the screenshot below (from janczizikow/sleek/)

![image](https://user-images.githubusercontent.com/7832163/40821564-e1896746-6524-11e8-8ed1-2a6d17f52f11.png)

**Comment by chesterhow** [comment]
Hey @GammaGames really glad you like the theme! Hmm I think it shouldnt be too difficult to implement something like that. But i’m not sure about how familar you are with CSS? 

What i would do is wrap the title and date in a div. Within this div i’ll also include an img tag with my desired background. Then i’ll use the `position: absolute` property to sorta make the image occupy the “background” of the div.

**Comment by chesterhow** [comment]
Hmm, currently I don't think there is a huge demand for the `img` feature sorry :( But if you would like an example of how to use images in the front matter you can check out my other blog - https://github.com/bottleneckco/heritage-sg. Its built with the Tale theme too and I'm using images in the front matter there. Hope it serves as a useful reference! :)

**Comment by GammaGames** [comment]
Thank you, it does! That's a very nice theme as well!

**Comment by chesterhow** [comment]
Alright, feel free to ask me again if you need help! 😊

**Comment by GammaGames** [comment]
I found a nice alternative I'm gonna try out, based on  [Hydejack](https://qwtel.com/hydejack/). I can use a sidebar and set its background to whatever the post's featuredImage variable is.

![image](https://user-images.githubusercontent.com/7832163/40955663-9b33d836-6848-11e8-9385-a56bc971b2e8.png)

I've still got a bit of customizing to go before I'll be happy with it, but I think it's a nice clean middle ground. Thanks again!

**Comment by chesterhow** [comment]
Oh nice! Hyde is one of my favs too 👍
