### ISSUE TITLE
Scrollbar shifts content

### ISSUE THREAD

**Issue by danaugrs** [chesterhow/tale#28]
Hi - when the scrollbar appears the content is shifted to the left and when it disappears the content is shifted to the right. You can easily reproduce this on the demo by switching between the **About** and the **Posts** pages on the top right.

Here's a potential fix: https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page

**Comment by chesterhow** [comment]
Ah that is indeed kinda annoying. I quite like the first solution from that link! The one which uses:
```
html {
  overflow-y: scroll;
}
```

Would you like to make a pull request? :)

**Comment by danaugrs** [comment]
Done :) https://github.com/chesterhow/tale/pull/29

**Comment by prodingerd** [comment]
#29 does indeed fix the problem, now however, the scrollbar is always displayed, even if there is nothing to scroll. What do you think about the following, which would dynamically add a left margin to the HTML element, depending on whether there is a scrollbar or not?

    html { 
        margin-left: calc(100vw - 100%);
    }

**Comment by chesterhow** [comment]
Personally, I'm okay with having the scrollbar permanently there. I've tested it on various browsers on both MacOS and Windows and I think it's not too distracting. But if you prefer a dynamic scrollbar, feel free to fork the repo and implement it on your end 🙂
