### ISSUE TITLE
Add feed_meta

### ISSUE THREAD

**Issue by fwenzel** [chesterhow/tale#34]
To add an auto-generated RSS/atom feed, github pages says one needs to add

`{% feed_meta %}`

to the `<head>` of the document: https://help.github.com/articles/atom-rss-feeds-for-github-pages/

Could you do that?

**Comment by chesterhow** [comment]
@fwenzel That's actually a pretty good idea. Would you like to make a PR?

**Comment by vijeth-aradhya** [comment]
@chesterhow I have to admit that I loved the theme! :smile: Unfortunately, I am busy these days, but I'd love to contribute soon. Tags and archive are not yet included, right?

**Comment by fwenzel** [comment]
Yeah for sure, one sec

**Comment by chesterhow** [comment]
@vijeth-aradhya Thanks! I'm glad you like the theme :) To answer your question, nope, tags and archive features have not been implemented in this theme so far.
