### ISSUE TITLE
Does it have code highlighting?

### ISSUE THREAD

**Issue by eonist** [chesterhow/tale#4]
like:

```swift
print("hello world")
```

**Comment by chesterhow** [comment]
@eonist Yup! Check out the post titled "Example Content" for some examples.

**Comment by eonist** [comment]
Super cool! I saw that page but didn't scroll far enough :( Your theme is My new favourite Jekyll theme. :D

**Comment by chesterhow** [comment]
@eonist No worries and thank you!! :)
