### ISSUE TITLE
Self-hosted solutions require nginx rewrite

### ISSUE THREAD

**Issue by ikaruswill** [chesterhow/tale#43]
Hey man! Been a while, how's it going?

So I was trying out Jekyll with your theme as a disposable micro-site solution by using a hexadecimal hash as a subdomain. Great minimal theme for simple uses man.

I realise that in your _config.yml, you wrote:

```yaml
permalink:  /:year-:month-:day/:title
```

you omitted the trailing `:output_ext`

When running `jekyll serve`, there is no issue. However, on self-hosted solutions, there may be a problem where the server will attempt to load the `.html` posts without the extension, and respond with a 404.

I was running with an nginx server behind a load balancer.

What I did was to add the following into the server {} block in the nginx site config:

```nginx
# Remove trailing .html extension
rewrite ^(/.*)\.html(\?.*)?$ $1$2 permanent;
  
# Remove trailing slashes
rewrite ^/(.*)/$ /$1 permanent; 
```

This rewrite rule basically permits the omission of the extension in the links. 

Perhaps it'd be good to add into the README.md if this is true.

**Comment by chesterhow** [comment]
Ahh, thanks for bringing this up. Never knew it was an issue for self-hosted solutions. There seems to be a recommended nginx configuration for extensionless permalinks on the Jekyll docs.

https://jekyllrb.com/docs/permalinks/#extensionless-permalinks

**Comment by ikaruswill** [comment]
Interesting, that's actually a more minimalistic approach.

Not having people bring this up probably is a good indicator of how few people host their own sites out there lol.

### Brain dump

**My solution**
Request to `2018-08-25/hello-world.html` --> `2018-08-25/hello-world`

**[Jekyll solution](https://jekyllrb.com/docs/permalinks/#extensionless-permalinks)**
A request to `2018-08-25/hello-world.html` --> `2018-08-25/hello-world.html`


### Thoughts

* My solution may be aesthetically desirable if the domain/subdomain was not shared with any other sites. 
* If the server is shared, the Jekyll approach is probably safer, where a `.html` request still ends up with a `.html` path in the address bar.

Thanks for the link, and keep up the good stuff!

**Comment by chesterhow** [comment]
Nice thanks for breaking it down for others to see as well 👍 Thanks @ikaruswill , will be closing this for now 😄

**Comment by trmckay** [comment]
Hey thanks for posting this, really helped me out!
