### ISSUE TITLE
Post links aren't updating

### ISSUE THREAD

**Issue by 2018sjain** [chesterhow/tale#5]
Hi, this is my first time using Jekyll, so I may just be making a simple mistake. I've forked the repository and have changed all the needed variables in the configurations file. I also changed the base url to /tale. Unfortunately, the links for the posts still link to the posts on your website, instead of reading the config file and linking to my website.

**Comment by chesterhow** [comment]
Your website looks like its working fine to me. Think you already fixed it :) Shall close this for now

**Comment by 2018sjain** [comment]
Yup, a lot of testing and I got it working. Just in case anybody runs in to this same problem, I'll put my solution here.

Since I used gh-pages to put my blog on a link like _mywebsite.com/blog_ instead of just _mywebsite.com_, the urls for the posts and about section would link to nonexisting entities such as mywebsite.com/2017/08/24/post, which SHOULD have been mywebsite.com/**blog**/2017/08/24/post.

To fix this, find the sections in the _default.html_, _post.html_, and _index.html_ that include Jekyll input for `prepend: site.url`. For example in _default.html_ there is `<li><a href="{{ '/about' | prepend: site.url }}">About</a></li>`. Just include prepend:site.baseurl if you're in the same situation as me. Therefore, it would become `<li><a href="{{ '/about' | **prepend: site.baseurl** | prepend: site.url }}">About</a></li>`.

Hope this helps anybody that is stuck!

**Comment by chesterhow** [comment]
@2018sjain Hmm, alternatively you could change the site url field in the config file to be "mywebsite.com/blog" instead of "mywebsite.com". Hope this helps :)

**Comment by 2018sjain** [comment]
I actually tried that, but unfortunately there was an issue with the _style.css_ file not being accessed. However, this is my first time using Jekyll so there's a high chance I just made an error somewhere along the way.
