### ISSUE TITLE
Add cover image

### ISSUE THREAD

**Issue by kisvegabor** [chesterhow/tale#55]
Hi,

First of all, thank you for this great theme! :)

I'd like to ask how can I add a cover image to the posts listed on the home page. 

I modified `home.html` like this:
```html
 <div>
        <p style="float: left;"><img src="{{ post.cover }}" height="200px" width="200px" border="1px"></p>
        
        <time datetime="{{ post.date }}" class="catalogue-time">{{ post.date | date: "%B %d, %Y" }}</time>
        <h1 class="catalogue-title">{{ post.title }}</h1>
        <div class="catalogue-line"></div>

        <p>
            {{ post.content | strip_html | truncatewords: 30 }}
        </p>

 </div>
```
It works but:
1. the nice animated horizintal line is covered by the image 
2. it's not responsive

Can you give some hints?

**Comment by chesterhow** [comment]
Can you show me a screenshot of how it looks as well? It's a little hard to visualise based on code alone 😅

**Comment by kisvegabor** [comment]
Sure, here is the website:
http://blog.littlevgl.com/
https://github.com/littlevgl/blog

**Comment by chesterhow** [comment]
Looks like you got it fixed already! 👍

**Comment by kisvegabor** [comment]
Yes, I finally made it work. However I'm not a professional web developer, so I've just hacked it.
If somebody needs a similar feature can check my implementation as a reference.

Anyway, thank you for the answers and this great theme!
