### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by behroozramezani** [chesterhow/tale#6]
Hello
I'm new in jekyll. I forked you repo and add my config to it. when run jekyll on localhost everything is ok. but when i push jekyll to github. i find some issue. first i give you some information about config file
my _config.yml
```
# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Tale
paginate:       5
baseurl:        "/"
url:            "" 

# Assets
sass:
  sass_dir:     "../_sass"
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Chester How
  url:          http://chester.how
  email:        chesterhow@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
```
I go to this link
https://behroozramezani.github.io/mr.ramezani/
my site load but when i open any post link or open about link i got an error 404
![screenshot_20171006_150350](https://user-images.githubusercontent.com/17659342/31276225-984fe8e4-aaa7-11e7-983c-6cfd373088d7.png)

**Comment by chesterhow** [comment]
@behroozramezani hmm.. did you enable github pages in that repository settings?

**Comment by behroozramezani** [comment]
yes i did
![screenshot_20171006_162856](https://user-images.githubusercontent.com/17659342/31278850-8491f980-aab3-11e7-9b46-9ab97a8c7bf5.png)

**Comment by chesterhow** [comment]
@behroozramezani try the link again! It’s working for me now :) Maybe you tried too early and github pages wasnt ready yet.

**Comment by behroozramezani** [comment]
Yes i fix issue. 
Thanks
