### ISSUE TITLE
Display is set to `inline-block` on `catalogue-item`

### ISSUE THREAD

**Issue by schdck** [chesterhow/tale#66]
Hey!

First, thanks for the great theme.

While testing my website I realized that the `display` property is set to `inline-block` on the `catalogue-item`. 

This is fine when the post's content is big, but for small/empty posts, it produces the following result on the `index.html` page:

![image](https://user-images.githubusercontent.com/16804291/64564305-9942fc00-d327-11e9-9f6a-297d76981389.png)

The error seems to go away just by setting the value of the property to `block` on [**this**](https://github.com/chesterhow/tale/blob/afb3afa9da535c041602ce531effdce5c069a6dd/_sass/tale/_catalogue.scss#L5) line of the `_catalogue.scss` file.

I would open a PR, but didn't know if this was intentional or not.

**Comment by chesterhow** [comment]
Hey @schdck that's a good catch! Yup changing it to block seems like a good fix. Go ahead and make a PR :)

**Comment by schdck** [comment]
Here you go :)
