### ISSUE TITLE
Banner idea

### ISSUE THREAD

**Issue by KingJacM** [chesterhow/tale#84]
Hello:

I really liked your website, but I really wanted to have a banner(full width). However, as a beginner, I actually don't know how to create a banner on this Jekyll template. 

Do you think you might be able to add this feature? @chesterhow 

Thank you

**Comment by Jasonwi** [comment]
@KingJacM Maybe you just want to expand navi-bar width ?
![image](https://user-images.githubusercontent.com/59698185/83937665-759eda80-a801-11ea-9bc1-d72e089977d6.png)

**Comment by chesterhow** [comment]
@KingJacM glad you like the theme! Unfortunately, I will not be adding banner images to the theme. However, you can check out this blog https://github.com/bottleneckco/heritage-sg where I added a banner image to the Tale theme. Hope this helps!
