### ISSUE TITLE
I found if the content is write by Chinese, and when browse the home page, It will show many lines. 

### ISSUE THREAD

**Issue by accordionmaster** [chesterhow/tale#95]
I found if the content is write by Chinese, and when browse the home page, It will show many lines. ,h ow can I handle this problem.  Thank you very much.

**Comment by chesterhow** [comment]
@accordionmaster I've fixed this in #98. Do have a look at https://chesterhow.github.io/tale/2021-04-30/managing-excerpt on how to manually customise the excerpt for each post :)
